FROM node:18-alpine as base

ARG DB_PROVIDER="sqlite"
ENV DB_PROVIDER=${DB_PROVIDER}

WORKDIR /app

FROM base as deps

RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci --ignore-scripts

FROM deps as build

COPY . .

RUN npm run postinstall && \
    npm run build:ks 

CMD DB_PROVIDER=${DB_PROVIDER} npm run start:ks
