# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "seogen"
primary_region = "syd"

[build]
dockerfile = "Dockerfile.admin"

[build.args]
DB_PROVIDER = "postgresql"

[env]
KS_PORT = "3000"
# DATABASE_URL = "" # secret
NEXT_PUBLIC_GRAPHQL_PATH = "/api/graphql"
NEXT_PUBLIC_SERVER_URL = "https://seogen.fly.dev"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512
